### ISSUE TITLE
Debug TypeError using Python 3.8

### ISSUE THREAD

**Issue by DeuteriumQ** [yamnikov-oleg/switch-layout#8]
Script works like a charm on my Elementary OS 5.1. But when first configuring the script I've met an issue with using membership operator for checking if key is Key or KeyCode.
Following code raises TypeError exception when using Python 3.8, but does not when using  Python 3.6 (both have pynput 1.6.8)
```Python
    if key in keyboard.Key:
        return "keyboard.Key.{}".format(key.name)
    else:
        return "keyboard.KeyCode({})".format(key.vk)

 # Exception
Traceback (most recent call last):
  File "/usr/lib/scripts/switch-layout.py", line 110, in <module>
    main()
  File "/usr/lib/scripts/switch-layout.py", line 106, in main
    listener.join()
  File "/home/deuterium/.local/lib/python3.8/site-packages/pynput/_util/__init__.py", line 210, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "/home/deuterium/.local/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/deuterium/.local/lib/python3.8/site-packages/pynput/_util/__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "/home/deuterium/.local/lib/python3.8/site-packages/pynput/_util/xorg.py", line 458, in _handler
    self._handle(self._display_stop, event)
  File "/home/deuterium/.local/lib/python3.8/site-packages/pynput/keyboard/_xorg.py", line 549, in _handle
    self.on_press(key)
  File "/home/deuterium/.local/lib/python3.8/site-packages/pynput/_util/__init__.py", line 78, in inner
    if f(*args) is False:
  File "/usr/lib/scripts/switch-layout.py", line 51, in on_press
    print("Pressed: {}".format(format_key(key)))
  File "/usr/lib/scripts/switch-layout.py", line 32, in format_key
    if key in keyboard.Key:
  File "/usr/lib/python3.8/enum.py", line 310, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'KeyCode' and 'EnumMeta'
```
Simply checking, if key object is instance of keyboard.Key does the trick, but being relatively new to Python I'm not sure why it behaves differently in 3.6 and 3.8 in the first place.
```Python
    if isinstance(key, keyboard.Key):
        return "keyboard.Key.{}".format(key.name)
    else:
        return "keyboard.KeyCode({})".format(key.vk)
```

**Comment by yamnikov-oleg** [comment]
You're right. It looks like they have changed `Enum` behaviour slightly in 3.7 or 3.8. `isinstance` works correctly.

Thank you for reporting this.

Could you make a PR with your fix so I could merge it under your name?
